name: CD-Develop

on:
  workflow_run:
    workflows: ["ci-build-dev"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: tag
          path: artifact

      - name: Build docker image with tag
        run: |
          tag=$(cat artifact/tag)
          template="./github/templates/docker-compose.yml"
          output="./docker-compose.yml"

          SED -e "s/\${{ BACKEND_VERSION }}/$tag/" \ 
          $template > $output

      - name: Push to repository
        run: |
          git config --global ${{ vars.email }}
          git config --global user.name ${{ vars.username }}
          git add .
          git commit -m "Update docker-compose.yml with new tag"
          git push