name: CI-Build-Dev

on:
  push:
    branches:
      - develop

jobs:
  build-dev-image:
    runs-on: ubuntu-latest
    name: Build and push docker image to docker hub

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build -t tamatini/devops-lessons-backend .
        
      - name: Add tag to docker image
        run: |
          docker tag tamatini/devops-lessons-backend tamatini/devops-lessons-backend:${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}.${{ github.run_number }}

      - name: Push docker image to docker hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push tamatini/devops-lessons-backend:${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}.${GITHUB_RUN_NUMBER}

      - name: Create artifact file
        run: |
          mkdir artifact
          touch artifact/tag
          echo ${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}.${GITHUB_RUN_NUMBER} > artifact/tag

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tag
          path: artifact/

  create-docker-compose:
    runs-on: ubuntu-latest
    name: Create docker-compose.yml file
    needs: build-dev-image

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: tag

      - name: test artifact download
        run: |
          ls -R

      - name: Build docker image with tag
        run: |
          tag=$(cat tag)
          ls -R .github
          template=".github/templates/docker-compose.template"
          output="./docker-compose.yml"

          sed -e "s/\${BACKEND_VERSION}/$tag/" \
          $template > $output

      - name: Push to repository
        run: |
          git config --global ${{ vars.email }}
          git config --global user.name ${{ vars.username }}
          git add .
          git commit -m "Update docker-compose.yml with new tag"
          git push