name: PR-CI

on:
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: CI Test
      uses: actions/setup-node@v4
      with:
        node-version: '20.11'
    - run: npm run build --if-present
    - run: npm run test
